name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.json'
      - 'deploy/**'
      - 'apps/**'
      - 'packages/**'
      - 'tests/**'
      - 'turbo.json'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  ci:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test

  cdk-synth:
    name: CDK Synth
    needs: ci
    runs-on: ubuntu-latest
    env:
      CDK_DISABLE_TELEMETRY: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Root Dependencies
        run: yarn install --frozen-lockfile
      - name: Install Deploy Dependencies
        run: |
          cd deploy
          yarn install --frozen-lockfile
      - name: CDK Synth
        working-directory: deploy
        run: yarn run cdk synth --quiet

  tf-validate:
    name: Terraform Validate
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'
      - name: Validate Cloudflare Terraform
        working-directory: deploy/terraform/cloudfront
        env:
          TF_VAR_api_origin: "example.com"
        run: |
          terraform init -backend=false
          terraform validate