name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  id-token: write

jobs:
  prerelease:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - name: Version and publish
        run: |
          # Try changeset first
          npx changeset version --snapshot prerelease.${{ github.sha }} || {
            echo "No changesets found, using npm version for prerelease"
            cd packages/tsconfig && npm version prerelease --preid=${{ github.sha }} && npm publish --provenance --access public
            cd ../inscriptions && npm version prerelease --preid=${{ github.sha }} && npm publish --provenance --access public
            exit 0
          }

          # If changeset succeeded, build and publish
          yarn workspaces run build
          cd packages/tsconfig && npm publish --provenance --access public --prerelease
          cd ../inscriptions && npm publish --provenance --access public --prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - name: Version and publish packages
        uses: changesets/action@v1
        with:
          publish: yarn workspaces foreach npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
