name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  id-token: write

jobs:
  prerelease:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - name: Version and publish
        run: |
          # First try changeset versioning
          npx changeset version --snapshot prerelease.${{ github.sha }}

          # Build all packages
          yarn workspaces run build

          # Publish each package, using npm version if no changeset was applied
          for pkg in tsconfig inscriptions; do
            cd packages/$pkg
            if grep -q "prerelease.${{ github.sha }}" package.json; then
              echo "Publishing $pkg with changeset version"
              npm publish --provenance --access public --prerelease
            else
              echo "No changeset for $pkg, using npm version"
              npm version prerelease --preid=${{ github.sha }} && npm publish --provenance --access public
            fi
            cd ../..
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - name: Version and publish packages
        uses: changesets/action@v1
        with:
          publish: yarn workspaces foreach npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
